version: "2.1"
services:
  config-server:
    image: project-example/config-service
    ports:
     - 6818:8888
  etcd:
    image: quay.io/coreos/etcd
    ports:
     - 2379:2379
  db-investigation:
    image: postgres
    ports:
     - 15432:5432
  db-bulk:
    image: postgres
    ports:
     - 15432:5432