search:
  config: training
  elastic.datasources:
    customer:
      index: search-test-customer
      type: customer
    hotlist:
      index: search-test-hotlist
      type: hotlist

resolver.elastic:
  datasources:
    customer:
      indexPrefix: resolver-test-customer
    hotlist:
      indexPrefix: resolver-test-hotlist

elastic:
  instances:
    default:
      uri: elasticsearch://localhost:19200

elastic.instances:
  my-instance:
    uri: elasticsearch://localhost:19200

scoring.elastic.instance: my-instance
