database.type: postgres

acl.database:
  autocreate: true
  type: postgres
  slick:
    profile: slick.jdbc.PostgresProfile$
    db:
      url: jdbc:postgresql://127.0.0.1:5432/acl?user=postgres&password=postgres
      driver: org.postgresql.Driver
      numThreads: 10
      connectionTimeout: 10000

connect.database:
  autocreate: true
  type: postgres
  slick:
    profile: slick.jdbc.PostgresProfile$
    db:
      url: jdbc:postgresql://127.0.0.1:5432/connect?user=postgres&password=postgres
      driver: org.postgresql.Driver
      numThreads: 10
      connectionTimeout: 10000

security.database:
  autocreate: true
  type: postgres
  slick:
    profile: slick.jdbc.PostgresProfile$
    db:
      url: jdbc:postgresql://127.0.0.1:5432/security?user=postgres&password=postgres
      driver: org.postgresql.Driver
      numThreads: 10
      connectionTimeout: 10000

intelligence.database:
  autocreate: true
  type: postgres
  slick:
    profile: slick.jdbc.PostgresProfile$
    db:
      url: jdbc:postgresql://127.0.0.1:5432/explorer_investigation?user=postgres&password=postgres
      driver: org.postgresql.Driver
      numThreads: 10
      connectionTimeout: 10000

investigation.database:
  autocreate: true
  type: postgres
  slick:
    profile: slick.jdbc.PostgresProfile$
    db:
      url: jdbc:postgresql://127.0.0.1:5432/explorer_investigation?user=postgres&password=postgres
      driver: org.postgresql.Driver
      numThreads: 10
      connectionTimeout: 10000

task.database:
  autocreate: true
  type: postgres
  slick:
    profile: slick.jdbc.PostgresProfile$
    db:
      url: jdbc:postgresql://127.0.0.1:5432/task?user=postgres&password=postgres
      driver: org.postgresql.Driver
      numThreads: 10
      connectionTimeout: 10000
