spring.application.name: configserver

spring.profiles.active: dev

server.port: 8888

spring:
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: configserver
    etcd:
      discovery:
        discoveryPrefix: /quantexa/explorer

quantexa.security.authentication:
  instance-role: user
  jwt.secret: hxF^yDQNnA4/M'94_*\BnT7sN`8X]GS%^z#C8?zdwJ'2L6{(G%D"QkmSWEte-;@N

---

spring.profiles: dev

spring.profiles.include:
  - native

spring.cloud.etcd.uris: http://localhost:2379

---

spring.profiles: docker

spring.profiles.include:
  - native

spring.cloud.etcd.uris: http://etcd:2379

spring.cloud.config.server:
  native.searchLocations: file:////config-yml-files
  overrides.config-files.dir: file:////config-files
  overrides.quantexa.licence.path: file:////quantexa-licence/quantexa.licence

---

spring.profiles: docker-production

spring.cloud.config.server.overrides:
  elastic.url: elasticsearch://quantexa-elastic:9200

---

spring.profiles: kubernetes

spring.cloud.config.server:
  overrides:
    bulk-search.database.password: ${POSTGRES_PASSWORD}
    security.database.password: ${POSTGRES_PASSWORD}
    slick.db.password: ${POSTGRES_PASSWORD}

spring:
  cloud:
    config:
      discovery.enabled: false
      uri: http://config-server.${NAMESPACE}.svc.cluster.local:8888
    etcd:
      discovery.enabled: false
      uris:  http://etcd.${NAMESPACE}.svc.cluster.local:2379
